name: star
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.5
  - astropy=4.2
  - ipython=7.17.0
  - jupyter_nbextensions_configurator
  - jupyter_server=1.11.0  
  - lightkurve=2.0.10
  - matplotlib=3.3.4
  - notebook=6.1.3
  - numpy=1.19.5
  - pdoc3=0.10.0
  - scipy=1.6.0

  
  
  
  
  
  
  
  
  
  
  
  
